### PR TITLE
add testnet3 support and pass policy

### PR DESCRIPTION
**Pull request by gregdhill**
Testnet Compatibility & Better Password Enforcement

The API wrappers have been updated to support URI changes, primarily for switching the mode. Due to issues with weak passwords in [brain wallets](https://fc16.ifca.ai/preproceedings/36_Vasek.pdf) it is better to enforce stronger tokens. This is implemented by way of Shannon's Entropy to score the probability distribution of chars and threshold at a reasonable level.

### CODE REVIEW

**Comment by josephcastan** [comment]
@gregdhill Thanks for the patch.

I think testnet makes more sense as its own backend. It's also probably better to make a separate copy of the wallet, so as not to complicate the main code. I will do it later today.

Also thanks for the entropy calculation, it's a good idea indeed!

**Comment by josephcastan** [comment]
@gregdhill Uploaded testnet version: https://tsbw.io/test/

Can you test it please? I have no coins.

**Comment by gregdhill** [comment]
Sure, seems to be working: https://testnet.blockchain.info/address/moHgEvii55mhXg2NfhgEWrcjcYqG3FwnF2

Site no longer longer defaults to https however: http://tsbw.io/

**Comment by josephcastan** [comment]
HTTP is an outdated version, added redirect to HTTPS instead.

**Pull request merged**
